#!/usr/bin/env python3
"""Write the auditable presentation-model provenance report."""
from __future__ import annotations

import json
from pathlib import Path

from project_paths import PROJECT_ROOT


ROOT = PROJECT_ROOT / "artifacts/results/all_age_groups_20260806"


def main() -> None:
    fp = json.loads((ROOT / "configs/presentation_model_fingerprint.json").read_text(encoding="utf-8"))
    text = f"""# Presentation model identification

## Conclusion

The presentation model is the retained natural layer-to-time VGG16 + four-choice Wong-Wang R5 diagnostic package. The exact mechanism figure is `{fp['mechanism_figure_source']}` and is generated by `code/scripts/run_real_vgg_target_flanker_dynamics_audit.py`. Its source trial-level behavior file is `{fp['source_trial_prediction_file']}`; the retained CAF figure and source table are under `{fp['presentation_model_result_dir']}/figures` and `{fp['presentation_model_result_dir']}/results`.

The corrected-equivalent is the choice-coupled schedule result under `{fp['corrected_model_result_dir']}`. It keeps VGG16, the five layerwise evidence arrays, `per_layer_gap_scale`, four-channel recurrent Wong-Wang, sustained crossing, and group non-decision time. It changes the schedule timing and binds choice to `winner_at_readout`, fixing the legacy mismatch in which RT used a sustained crossing but choice could use the whole trajectory.

## Evidence chain

`05_natural_emergence_evidence_chain.svg` -> `run_real_vgg_target_flanker_dynamics_audit.py` -> `trial_level_target_flanker_dynamics.csv` -> retained R5 predictions and cached layerwise evidence -> `run_representative_extreme_age_subset_fitting.py` -> `vgg_wongwang_lim.py::DiffDecisionMultiClass`.

The figure contains the three required stages: Layerwise evidence, Evidence sent to WW, and WW state. The code uses VGG layers `conv3`, `conv4`, `conv5`, `pooled`, and `final`; normalizes with `per_layer_gap_scale`; maps layers using `natural_smooth_5stage`; and reads a four-direction competitive trajectory with sustained crossing.

## Candidate comparison

- Retained R5: has young/older trial predictions, CAF, RT, mechanism tables, parameters, and the exact three-panel mechanism figure lineage. Choice rule is legacy `trajectory_max_choice`.
- Choice-coupled schedule: has all-age selected trial predictions, CAF, crossing fields, schedule parameters, and `winner_at_readout`. It is a corrected-equivalent, not a different visual architecture.
- Other `best`, `optimized`, and supervisor directories are treated as exploratory or supporting unless their trial-level lineage matches this chain.

## Extension decision

The extreme-group corrected predictions preserve early flanker/late target evidence, target recovery before readout on most correct trials, 100% crossing coverage, and the reported incongruent CAF recovery direction. The five intermediate groups now also have complete 5,000-trial VGG evidence caches and corrected-equivalent predictions. All seven groups use the same VGG layers, normalization reference, accumulator, sustained-crossing rule, choice-at-readout rule, candidate grid, score, and seed rule. Threshold and margin follow a declared linear interpolation between the retained extreme-age anchors; schedule and non-decision-time terms are selected per group.

## Fixed identity

- VGG: `{fp['vgg_architecture']}`; layers: `{', '.join(fp['vgg_layers_used'])}`
- evidence: `{fp['evidence_definition']}`; normalization: `{fp['evidence_normalization']}`
- WW: `{fp['ww_architecture']}`
- RT: `{fp['rt_rule']}`; crossing: `{fp['crossing_rule']}`; no crossing: `{fp['no_crossing_rule']}`
- decision class: `{fp['decision_class_name']}`; seed: `{fp['random_seed']}`
- unified predictions: `{fp['unified_trial_prediction_file']}`

This is now a complete seven-group representative-subset extension. It remains diagnostic rather than a held-out or full-cohort fit, and the age trend is descriptive rather than causal.
"""
    (ROOT / "audits/presentation_model_identification.md").write_text(text, encoding="utf-8")
    (ROOT / "summaries/presentation_model_identification.md").write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
